### Loading Libraries and Data

In [244]:
#Basic needed libraries
import pandas as pd
import numpy as np

#Visualization
import plotly.express as px

#Model and metrics
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [245]:
data = np.array([[20, 1000], [27, 1200], [21, 2900], [37, 1850], 
                [46, 900], [53, 950], [55, 2000], [47, 2100],
                [52, 3000], [32, 5900], [39, 4100], [41, 5100],
                [39, 7000], [48, 5000], [48, 6500]])
data

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [246]:
#data = pd.DataFrame(data=data_np, columns=['age', 'salary'])
#data

In [247]:
#fig = px.scatter(x=data[:,0], y=data[:,1])
#fig.show()

In [248]:
scaler = StandardScaler()
data_scaler = scaler.fit_transform(data)

In [249]:
data_scaler

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

In [250]:
kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(data_scaler)

In [251]:
centroids = kmeans.cluster_centers_
centroids

array([[ 0.07703438,  1.11413572],
       [-0.05135625, -0.74275714]])

In [252]:
scaler.inverse_transform(centroids)

array([[  41.16666667, 5600.        ],
       [  39.77777778, 1766.66666667]])

In [253]:
labels = kmeans.labels_
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [254]:
fig_results = px.scatter(x=data[:,0], y=data[:,1], color=labels)
fig_results.show()

In [255]:
for i in range(1,len(data)):
    print(data[i], labels[i])

[  27 1200] 1
[  21 2900] 1
[  37 1850] 1
[ 46 900] 1
[ 53 950] 1
[  55 2000] 1
[  47 2100] 1
[  52 3000] 1
[  32 5900] 0
[  39 4100] 0
[  41 5100] 0
[  39 7000] 0
[  48 5000] 0
[  48 6500] 0


In [256]:
import plotly.graph_objects as go

In [257]:
data = pd.DataFrame(data=data, columns=['age', 'salary'])
data['cluster'] = labels
data

age  salary  cluster
0    20    1000        1
1    27    1200        1
2    21    2900        1
3    37    1850        1
4    46     900        1
5    53     950        1
6    55    2000        1
7    47    2100        1
8    52    3000        1
9    32    5900        0
10   39    4100        0
11   41    5100        0
12   39    7000        0
13   48    5000        0
14   48    6500        0

In [261]:
fig = go.Figure()

data_cluster0 = data[data['cluster'] == 0].copy()
data_cluster1 = data[data['cluster'] == 1].copy()

fig.add_trace(go.Scatter(x=data_cluster0['age'], y=data_cluster0['salary'], mode='markers', name='cluster 0'))
fig.add_trace(go.Scatter(x=data_cluster1['age'], y=data_cluster1['salary'], mode='markers', name='cluster 1'))