### Loading Libraries and Data

In [21]:
#Basic needed libraries
import pandas as pd
import numpy as np

#Visualization
import plotly.express as px

#Model and metrics
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn import metrics

In [29]:
data = np.array([[20, 1000], [27, 1200], [21, 2900], [37, 1850], 
                [46, 900], [53, 950], [55, 2000], [47, 2100],
                [52, 3000], [32, 5900], [39, 4100], [41, 5100],
                [39, 7000], [48, 5000], [48, 6500]])
data

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 4100],
       [  41, 5100],
       [  39, 7000],
       [  48, 5000],
       [  48, 6500]])

In [33]:
fig = px.scatter(x=data[:,0], y=data[:,1])
fig.show()

In [22]:
scaler = StandardScaler()
data_scaler = scaler.fit_transform(data)

In [ ]:
data_scaler

In [23]:
kmeans = KMeans(n_clusters=2, random_state=0, n_init="auto").fit(data_scaler)

In [39]:
centroids = kmeans.cluster_centers_
centroids

array([[ 0.07703438,  1.11413572],
       [-0.05135625, -0.74275714]])

In [40]:
scaler.inverse_transform(centroids)

array([[  41.16666667, 5600.        ],
       [  39.77777778, 1766.66666667]])

In [28]:
labels = kmeans.labels_
labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [42]:
fig_results = px.scatter(x=data[:,0], y=data[:,1], color=labels)
fig_results.show()